### PR TITLE
Initial screens and link screens setup

### PR DESCRIPTION
**Pull request by adam-k4**
Just added the screens themselves without functionality yet, made some currentUser changes for handling logins in a way that keeps the stack consistent (no amibugity in which function called mainmenu)

Also put jobs.json in the gitignore together with users

### CODE REVIEW

**Comment by adam-k4** [comment]
Merge my general-links branch into this first

**Comment by ScumbagScalawag** [comment]
@zackzack38 not sure if this is known, but `test_general.py::testPrintGeneralSignUpNotShown` is failing, but only when you run `pytest tests/test_general.py` and `pytest`. For some reason it actually works if you run `pytest tests/test_general.py::testPrintGeneralSignUpNotShown`, along with all the other functions individually. 

image

**Comment by zackzack38** [comment]
The test failing is caused by a bug in the general print options logic where it adds the two lines every time it gets called. It is using the modified general print from the other tests.

**Comment by adam-k4** [comment]
Is https://github.com/ScumbagScalawag/In-College/pull/18#issuecomment-1742135806 this fixed? @zackzack38 @ScumbagScalawag

**Comment by ScumbagScalawag** [comment]
`general-links` Is merged into this and this branch is merged into `user-object`, so I'm marking this branch stale. All these changes will be included inside `user-object`. I'll circle back to this bug once the dust settles and see if it's still a problem/not solved yet.

**Pull request closed without merging**
